external_components:
  - source: 
      type: git
      url: https://github.com/lskov/esphome_components
      ref: main
    refresh: 0s
    components: [genvexv2]

genvexv2:

select:
  - platform: genvexv2
    modbus_controller_id: genvex_modbus_controller
    name: "Genvex speed mode"
    id: genvex_speed_mode    
    address: 0x0000
    options:
      - "Off"
      - "1"
      - "2"
      - "3"
      - "4"
      
  # - platform: genvexv2
  #   modbus_controller_id: genvex_modbus_controller
  #   name: "Genvex timer"
  #   id: genvex_timer    
  #   address: 106
  #   options:
  #     - "Off"
  #     - "1"
  #     - "2"
  #     - "3"
  #     - "4"
  #     - "5"
  #     - "6"
  #     - "7"
  #     - "8"
  #     - "9"

sensor:
  - platform: modbus_controller
    modbus_controller_id: genvex_modbus_controller
    name: "Genvex temp t1"
    id: genvex_temp_t1
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: U_WORD
    register_type: read
    address: 0
    lambda: |-
      ESP_LOGD("T1", "Processing T1 using lambda");
      return ((x - 300) / 10);
      
