external_components:
  - source: 
      type: git
      url: https://github.com/jesperholstjh/esphome_components
      ref: main
    refresh: 0s
    components: [genvexv2]

genvexv2:


sensor:
  - platform: modbus_controller
    modbus_controller_id: genvex_modbus_controller
    name: "Genvex inlet fan"
    id: genvex_inlet_fan
    icon: mdi:fan
    unit_of_measurement: "%"
    value_type: U_WORD
    register_type: read
    address: 0x0009
