external_components:
  - source: 
      type: git
      url: https://github.com/jesperholstjh/esphome_components
      ref: main
    refresh: 0s
    components: [genvexv2]

genvexv2:


sensor:
  - platform: modbus_controller
    modbus_controller_id: genvex_modbus_controller
    name: "Genvex Controller Version"
    id: genvex_controller_version
    address: 0x0200  # Modbus register 3x0200, prefix '3x' is usually omitted in the address
    value_type: U_WORD
    register_type: read
    unit_of_measurement: ""
    accuracy_decimals: 1
    icon: mdi:information-outline
    lambda: |-
      return x * 0.1;  # Since 1 unit is equal to 0.1 in the actual value

  - platform: status
    name: "Genvex Controller Status"
