external_components:
  - source: 
      type: git
      url: https://github.com/lskov/esphome_components
      ref: main
    refresh: 0s
    components: [genvexv2]

genvexv2:


sensor:
  - platform: modbus_controller
    modbus_controller_id: genvex_modbus_controller
    name: "Genvex Controller Version"
    id: genvex_controller_version
    address: 0x0200  # Modbus register 3x0200, prefix '3x' is usually omitted in the address
    value_type: U_WORD
    register_type: read
    unit_of_measurement: ""
    accuracy_decimals: 1
    icon: mdi:information-outline
    lambda: |-
      return x * 0.1;  # Since 1 unit is equal to 0.1 in the actual value



select:
  - platform: genvexv2
    modbus_controller_id: genvex_modbus_controller
    name: "Genvex speed mode"
    id: genvex_speed_mode    
    address: 0x0000
    options:
      - "Off"
      - "1"
      - "2"
      - "3"
      - "4"
      
  # - platform: genvexv2
  #   modbus_controller_id: genvex_modbus_controller
  #   name: "Genvex timer"
  #   id: genvex_timer    
  #   address: 106
  #   options:
  #     - "Off"
  #     - "1"
  #     - "2"
  #     - "3"
  #     - "4"
  #     - "5"
  #     - "6"
  #     - "7"
  #     - "8"
  #     - "9"

sensor:
  - platform: modbus_controller
    modbus_controller_id: genvex_modbus_controller
    name: "Genvex temp t1"
    id: genvex_temp_t1
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: U_WORD
    register_type: read
    address: 0
    lambda: |-
      ESP_LOGD("T1", "Processing T1 using lambda");
      return ((x - 300) / 10);

  - platform: modbus_controller
      modbus_controller_id: genvex_modbus_controller
      name: "Genvex inlet fan"
      id: genvex_inlet_fan
      icon: mdi:fan
      unit_of_measurement: "%"
      value_type: U_WORD
      register_type: read
      address: 102
